---
title: "Connecting research to enterpreneurship: The power of European Digital Innovation Hubs"
format:
  revealjs:
    width: 1920
    height: 1080
    transition: fade
    fontsize: "60px"
    slide-number: true
    menu: false
    logo: images/logo.png
css: styles.css
---

## Healthcare observational databases

\
\

- Increasingly used for medical research and policy-making
- Partly powered by the advances in interoperability
- OHDSI: one of the main drivers for interoperability

## Papageorgiou General Hospital

\
\

- Large hospital in the northern part of Greece
- Data on more than 1.4 million patients over the past 15 years
- Mapped to OMOP-CDM

## Papageorgiou General Hospital

\
\

Our main contributions are:

  - Mapping and updating the EHR to conform with OMOP-CDM
  - Building and executing software for analyzing this data
  - Assisting interested parties in the development and execution of study protocols
  

## EHDEN Mega-Study

\
\

> **Aim**
>
> Evluate incidence and prevalence of drugs with suggested shortages from 2010 to 2024

## EHDEN Mega-Study

\
\

- New way of analyzing real-world healthcare data
- Study leveraged data from all over Europe and N. America
  - 52 databases in total
  - 18 countries
- No other database from Greece other than PGH participated

## DARWIN EU

\
\

> **Aim**
> 
> Support EMA on the:
>
>  - Evaluation of safety and efficacy of medicines
>  - Evaluation of drug use and drug shortages

## DARWIN EU

\
\

- Project funded by the EMA
- Builds on top of EHDEN
- PGH has joined the list of the DARWIN EU approved healthcare databases
- Already received the first order for the execution of a study

## OHDSI Evidence Network

\
\

> **Aim**
>
> Create an easily accessible pool of the databases mapped to OMOP-CDM

## OHDSI Evidence Network

\
\

- Facilitate contact between parties executing a study and data sources
- Pre-executed diagnostics studies for each data source
- Extensive set of tools for out-of-the-box analyses

## Studies in collaboration with hospital doctors

\
\

> **Aim** 
>
> To involve the hospital doctors in the analysis of their own data to answer relevant questions driven by their
> everyday work

## Studies in collaboration with hospital doctors

\
\

Currently exploring the development and execution of study protocols:

  - Study of rhabdomyolysis patients 
  - Study of pre-eclampsia patients
  - Study of stroke patients

## Pharamceutical industry

\
\

- Collaboration with pharmaceutical industry to explore rare diseases
- Doctors were involved from the beginning
- Carefully planned protocol developed with the appropriate expertise
- Pilot study

## Challenges

\
\

- Data collection is fragmented 
- Digitization in many cases is still in very early stages
- National regulatory authorities do not prioritize analysis of healthcare observational data
- Disconnect from medical practitioners
- Pharmaceutical industry less interested in R&D in Greece using observational data

